apiVersion: v1 
kind: Service
metadata:
  name: svc-goserver
spec: 
  selector:
    app: goserver
  type: ClusterIP
  ports: 
  - name: goserver-http 
    port: 80
    targetPort: 8080
    protocol: TCP
